version: "3"  # Рекомендую явно указать версию
services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2567:2567"
    depends_on:
      - redis
      - nats
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - NATS_URL=nats://nats:4222
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS (если настроишь SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Файл конфигурации Nginx
    depends_on:
      - game-server
      - pocketbase

  # NATS
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Клиентский порт
      - "8222:8222"  # Мониторинг (опционально)
    command: "--jetstream"  # Включаем JetStream для продвинутых функций

  # PocketBase
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest  # Официальный образ
    ports:
      - "8090:8090"  # PocketBase по умолчанию на 8090
    volumes:
      - pocketbase-data:/pb_data  # Данные SQLite
      - pocketbase-migrations:/pb_migrations  # Миграции (опционально)
    command: --http="0.0.0.0:8090"  # Указываем порт и хост

volumes:
  grafana-storage: {}
  loki-data: {}
  pocketbase-data: {}
  pocketbase-migrations: {}