services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2567:2567"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana-storage: {}
  
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml