name: gamest
services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "2567:2567"
    depends_on:
      redis:
        condition: service_started
      nats:
        condition: service_started
      supabase-db:
        condition: service_healthy
      supabase-auth:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - ${SSL_CERT_PATH}:/etc/ssl/certs/gamest.pem
      - ${SSL_KEY_PATH}:/etc/ssl/private/gamest.key
    environment:
      NODE_ENV: ${NODE_ENV}
      NATS_URL: ${NATS_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SSL_CERT_PATH: /etc/ssl/certs/gamest.pem
      SSL_KEY_PATH: /etc/ssl/private/gamest.key

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: ${REDIS_URL}
    depends_on:
      redis:
        condition: service_started

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started

  loki:
    image: grafana/loki:latest
    ports:
      - "3101:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
      - -client.url=${LOKI_URL}/loki/api/v1/push
    depends_on:
      - loki

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      supabase-auth:
        condition: service_healthy
      supabase-db:
        condition: service_healthy
      supabase-realtime:
        condition: service_started
      game-server:
        condition: service_started
    restart: unless-stopped

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream"

  supabase-db:
    image: supabase/postgres:15.1.0.117
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db/01_init_auth.sql:/docker-entrypoint-initdb.d/01_init_auth.sql
      - ./volumes/db/02_roles.sql:/docker-entrypoint-initdb.d/02_roles.sql
      - ./volumes/db/03_realtime.sql:/docker-entrypoint-initdb.d/03_realtime.sql
      - ./volumes/db/04_init_admin.sql:/docker-entrypoint-initdb.d/04_init_admin.sql
      - ./volumes/db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - supabase-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  supabase-auth:
    image: supabase/gotrue:v2.170.0
    depends_on:
      supabase-db:
        condition: service_healthy
    ports:
      - "${AUTH_PORT}:8081"
    environment:
      GOTRUE_DB_SEARCH_PATH: ${GOTRUE_DB_NAMESPACE}
      GOTRUE_API_HOST: ${GOTRUE_API_HOST}
      GOTRUE_DB_DRIVER: ${GOTRUE_DB_DRIVER}
      GOTRUE_SITE_URL: ${GOTRUE_SITE_URL}
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_URI: ${GOTRUE_URI}
      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      GOTRUE_JWT_EXP: ${GOTRUE_JWT_EXP}
      GOTRUE_JWT_DEFAULT_GROUP_NAME: ${GOTRUE_JWT_DEFAULT_GROUP_NAME}
      GOTRUE_DB_NAMESPACE: ${GOTRUE_DB_NAMESPACE}
      GOTRUE_MAILER_AUTOCONFIRM: ${GOTRUE_MAILER_AUTOCONFIRM}
      GOTRUE_SMS_AUTOCONFIRM: ${GOTRUE_SMS_AUTOCONFIRM}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  supabase-studio:
    image: supabase/studio:latest
    ports:
      - "${STUDIO_PORT}:3000"
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_REST_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      DEFAULT_ORGANIZATION: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT: ${STUDIO_DEFAULT_PROJECT}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    depends_on:
      supabase-db:
        condition: service_healthy
      supabase-meta:
        condition: service_started

  supabase-meta:
    image: supabase/postgres-meta:v0.75.0
    depends_on:
      supabase-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: ${POSTGRES_USER}
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  supabase-realtime:
    image: supabase/realtime:v2.25.22
    depends_on:
      supabase-db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      SECRET_KEY_BASE: "your-super-secret-key-base-at-least-64-bytes-long-please-change-it"  # Замени на более длинный ключ
      PORT: 4000
      DB_HOST: ${DB_HOST:-supabase-db}  # Фallback на supabase-db
      DB_PORT: ${DB_PORT:-5432}         # Фallback на 5432
      DB_USER: ${POSTGRES_USER}         # Используем POSTGRES_USER
      DB_PASSWORD: ${POSTGRES_PASSWORD} # Используем POSTGRES_PASSWORD
      DB_NAME: ${POSTGRES_DB}
      SECURE_CHANNELS: 'true'
      JWT_SECRET: ${SUPABASE_JWT_SECRET}
      APP_NAME: ${APP_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  storage:
    image: supabase/storage-api:latest
    ports:
      - "${STORAGE_PORT}:5000"
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      SERVER_PORT: ${STORAGE_PORT}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}  # Добавлено для Storage
      DATABASE_URL: ${DATABASE_URL}
      STORAGE_BACKEND: ${STORAGE_BACKEND}
      STORAGE_FILE_BACKEND_PATH: ${STORAGE_FILE_BACKEND_PATH}
      UPLOAD_FILE_SIZE_LIMIT: ${UPLOAD_FILE_SIZE_LIMIT}
      UPLOAD_FILE_SIZE_LIMIT_STANDARD: ${UPLOAD_FILE_SIZE_LIMIT_STANDARD}
      UPLOAD_SIGNED_URL_EXPIRATION_TIME: ${UPLOAD_SIGNED_URL_EXPIRATION_TIME}
    volumes:
      - ./storage:/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  grafana-storage: {}
  prometheus-data: {}
  loki-data: {}
  supabase-db-data: {}