name: gamest
services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      nats:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: ${NODE_ENV}
      NATS_URL: ${NATS_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  redis:
    image: redis:7.4.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  prometheus:
    image: prom/prometheus:3.2.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: ${REDIS_URL}
    depends_on:
      redis:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  grafana:
    image: grafana/grafana:11.5.2
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  loki:
    image: grafana/loki:3.4.2
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  promtail:
    image: grafana/promtail:3.4.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
      - -client.url=${LOKI_URL}/loki/api/v1/push
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  nginx:
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      game-server:
        condition: service_started
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.1
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  nats:
    image: nats:2.10.26
    command: "--jetstream --http_port 8222"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  nats-exporter:
    image: natsio/prometheus-nats-exporter:0.16.0
    command:
      - "--varz"
      - "--connz"
      - "--healthz"
      - "http://nats:8222"
    depends_on:
      - nats
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

  node-exporter:
    image: prom/node-exporter:1.9.0
    container_name: gamest-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro  # Монтируем /proc для сбора метрик
      - /sys:/host/sys:ro    # Монтируем /sys для сбора метрик
      - /:/rootfs:ro         # Монтируем корневую файловую систему (только для чтения).
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gamest-shared-network

networks:
  gamest-shared-network:
    external: true

volumes:
  grafana-storage: {}
  prometheus-data: {}
  loki-data: {}