global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  - job_name: "game-server"
    static_configs:
      - targets: ["game-server:9567"]