global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Правила алертинга
rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Мониторинг Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    metrics_path: /metrics

  # Мониторинг игрового сервера
  - job_name: "game-server"
    static_configs:
      - targets: ["game-server:2567"]
    metrics_path: /metrics

  # Мониторинг NATS
  - job_name: "nats"
    static_configs:
      - targets: ['nats-exporter:7777']
    metrics_path: /metrics

  # Мониторинг Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Мониторинг Node.js
  - job_name: "nodejs"
    static_configs:
      - targets: ["game-server:2567"]
    metrics_path: /metrics

  # Мониторинг Nginx
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    metrics_path: /metrics

  # Мониторинг системы (node-exporter)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]  # Указываем порт node-exporter
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        regex: (.*):9100
        replacement: $1:9100
      - source_labels: [__meta_host]
        target_label: instance