name: Deploy GameST

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build client
      run: npm run build

    - name: Deploy to server
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        # Копируем весь проект (включая package.json)
        scp -o StrictHostKeyChecking=no -i deploy_key package.json dist server root@150.241.69.143:/opt/serv-game/
        ssh -o StrictHostKeyChecking=no -i deploy_key root@150.241.69.143 << 'EOF'
          cd /opt/serv-game
          npm install
          pm2 restart game-server || pm2 start server/index.js --name game-server
        EOF
        rm deploy_key