name: Deploy GameST

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build client
      run: npm run build

    - name: Deploy to server
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        scp -o StrictHostKeyChecking=no -i deploy_key -r dist server root@150.241.69.143:/opt/serv-game/
        scp -o StrictHostKeyChecking=no -i deploy_key package.json docker-compose.yml Dockerfile prometheus.yml loki-config.yml root@150.241.69.143:/opt/serv-game/
        ssh -o StrictHostKeyChecking=no -i deploy_key root@150.241.69.143 << 'EOF'
          cd /opt/serv-game
          docker-compose up -d --build
        EOF
        rm deploy_key